[package]
name = "heuristic_solver_eweidner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.submit]
inherits = 'release'


[dependencies]
rand = "*"
signal-hook = "*"
